# Generated by Django 5.0.1 on 2025-12-05 14:12

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Celery task ID', unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'upload_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Webhook endpoint URL', max_length=500)),
                ('events', models.JSONField(default=list, help_text="List of events to trigger this webhook (e.g., ['product.created', 'upload.completed'])")),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether this webhook is active')),
                ('secret_key', models.CharField(blank=True, help_text='Secret key for HMAC signature verification', max_length=64)),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retry attempts for failed deliveries')),
                ('failure_count', models.IntegerField(default=0, help_text='Consecutive failure count (auto-disables after threshold)')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Last time this webhook was triggered', null=True)),
                ('last_status_code', models.IntegerField(blank=True, help_text='HTTP status code from last delivery attempt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit - unique product identifier (case-insensitive)', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether the product is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['active', 'name'], name='active_name_idx'), models.Index(django.db.models.functions.text.Lower('sku'), name='sku_lower_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), name='unique_sku_lower'),
        ),
        migrations.AddIndex(
            model_name='uploadtask',
            index=models.Index(fields=['status', '-created_at'], name='status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['active', '-created_at'], name='webhook_active_idx'),
        ),
    ]
