# Generated by Django 5.0.1 on 2025-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtask',
            name='created_count',
            field=models.IntegerField(default=0, help_text='New products created'),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='duplicate_rows',
            field=models.IntegerField(default=0, help_text='Duplicate rows removed'),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='unique_products',
            field=models.IntegerField(default=0, help_text='Unique products after deduplication'),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='updated_count',
            field=models.IntegerField(default=0, help_text='Existing products updated'),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='failed_rows',
            field=models.IntegerField(default=0, help_text='Products that failed'),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='processed_rows',
            field=models.IntegerField(default=0, help_text='Products processed so far'),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='successful_rows',
            field=models.IntegerField(default=0, help_text='Products successfully saved'),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='total_rows',
            field=models.IntegerField(default=0, help_text='Total rows in CSV file'),
        ),
    ]
